apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: dockernaresh123/sampleapp
        resources:
         requests:
          cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
