apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: svc-sampleapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sampleapp
  type: LoadBalancer
status:
  loadBalancer: {}
